image:
- ubuntu1804

clone_depth: 3

build: off

init:
- sudo apt-get install -yq --no-install-suggests --no-install-recommends libhdf5-dev > /dev/null

install:
- cd app
- cmake ../src
- cmake --build .

test_script: ctest -V

