language: c
group: travis_latest

git:
  depth: 3
  quiet: true

os:
- osx

env: FC=gfortran

addons:
  apt:
    packages:
    - gfortran
    - libhdf5-dev

before_install:
- if [[ $TRAVIS_OS_NAME == osx ]]; then
    brew update > /dev/null;
    brew install gcc > /dev/null || brew link --overwrite gcc > /dev/null;
    export FC=gfortran;
    brew install hdf5 > /dev/null;
  fi

install:
- cd app
- cmake ../src
- cmake --build .

script: ctest -V

