bench_write – Object-oriented Fortran HDF5 interface
bench_write Subroutine
19 statements
Source File
public subroutine bench_write(file, layout, dat, N)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file
integer, intent(in) :: layout
real, intent(in) :: dat(:)
integer, intent(in) :: N
Calls
Called by
Contents
None
Call graph
bench_write calls sysclock2ms, write_layout, h5fcreate_f, h5fclose_f
write_layout calls h5dcreate_f, h5dclose_f, h5dwrite_f, h5sclose_f, h5pset_layout_f, h5pclose_f, h5pcreate_f
compact calls bench_write