bench_read – Object-oriented Fortran HDF5 interface
bench_read Subroutine
23 statements
Source File
public subroutine bench_read(file, N, dat)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file
integer, intent(in) :: N
real, intent(out), optional :: dat(:)
Calls
Called by
Contents
None
Call graph
bench_read calls sysclock2ms, h5fopen_f, h5ltread_dataset_float_f, h5fclose_f
compact calls bench_read