check – Object-oriented Fortran 2008 HDF5 interface
check Function
7 statements
Source File
public function check(ierr, msg)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ierr
character(len=*), intent(in) :: msg
Return Value logical
Called by
Contents
None
Call graph
lt3write calls check, lt3write
lt6write calls check, lt6write
hdf_close_group calls check, hdf_close_group
lt1read calls check, lt1read
hdf_open_group calls check, hdf_open_group
hdf_get_chunk calls check, hdf_get_chunk
lt2write calls check, lt2write
lt4write calls check, lt4write
hdf_get_layout calls check, hdf_get_layout
write_group calls check
lt7write calls check, lt7write
hdf_write_1d calls check, hdf_setup_write, hdf_write_1d
hdf_write_2d calls check, hdf_setup_write, hdf_write_2d
writeattr calls check, writeattr
hdf_setup_write calls check, hdf_set_deflate, hdf_shape_check
hdf_write_5d calls check, hdf_setup_write, hdf_write_5d
hdf_write_scalar calls check, hdf_setup_write, hdf_write_scalar
lt7read calls check, lt7read
lt5read calls check, lt5read
lt6read calls check, lt6read
lt0write calls check, lt0write
hdf_set_deflate calls check
lt0read calls check, lt0read
lt1write calls check, lt1write
hdf_write_4d calls check, hdf_setup_write, hdf_write_4d
hdf_wrapup calls check
hdf_write_7d calls check, hdf_setup_write, hdf_write_7d
hdf_initialize calls check
lt3read calls check, lt3read
hdf_shape_check calls check
hdf_write_8d calls check, hdf_setup_write, hdf_wrapup
hdf_write_3d calls check, hdf_setup_write, hdf_write_3d
hdf_finalize calls check
lt4read calls check, lt4read
lt2read calls check, lt2read
lt5write calls check, lt5write
hdf_write_6d calls check, hdf_setup_write, hdf_write_6d
hdf_read_7d calls hdf_shape_check, hdf_read_7d
hdf_read_4d calls hdf_shape_check, hdf_read_4d
hdf_read_6d calls hdf_shape_check, hdf_read_6d
hdf_read_2d calls hdf_shape_check, hdf_read_2d
hdf_read_5d calls hdf_shape_check, hdf_read_5d
hdf_read_3d calls hdf_shape_check, hdf_read_3d
hdf_read_1d calls hdf_shape_check, hdf_read_1d
hdf_read_scalar calls hdf_wrapup, hdf_read_scalar
h5write calls lt7write, lt3write, lt2write, lt1write, lt4write, lt6write, lt0write, lt5write
h5read calls lt3read, lt6read, lt2read, lt0read, lt4read, lt5read, lt1read, lt7read
test_exist calls h5write
test_readwrite_lt calls h5write, h5read
test_hdf5 calls test_readwrite_lt