close_file_image – Object-oriented Fortran HDF5 interface
close_file_image Subroutine
8 statements
Source File
public subroutine close_file_image(fapl_id)
close file image and library
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: fapl_id
Calls
Called by
Contents
None
Call graph
close_file_image calls h5pclose_f, h5close_f
test_file_image calls close_file_image