get_native_dtype – Object-oriented Fortran HDF5 interface
get_native_dtype Function
39 statements
Source File
function get_native_dtype(ds_id, dname, filename) result(native_dtype)
get the dataset variable type the "type" and "native_type" are just IDs, the final native type is composed from: * enddianness * generic type we think endianness is handled by HDF5 ... ? compose datatype inferred
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: ds_id
character(len=*), intent(in) :: dname
character(len=*), intent(in) :: filename
Return Value integer(kind=hid_t)
Calls
Called by
Contents
None
Call graph
get_native_dtype calls h5dget_type_f, h5tget_native_type_f, h5tget_class_f, h5tclose_f, h5tget_size_f
hdf_read_scalar calls get_native_dtype, hdf_read_scalar
hdf_read_3d calls get_native_dtype, hdf_read_3d
hdf_read_2d calls get_native_dtype, hdf_read_2d
hdf_read_7d calls get_native_dtype, hdf_read_7d
hdf_read_6d calls get_native_dtype, hdf_read_6d
hdf_read_4d calls get_native_dtype, hdf_read_4d
hdf_read_5d calls get_native_dtype, hdf_read_5d
hdf_read_1d calls get_native_dtype, hdf_read_1d