guess_chunk_size – Object-oriented Fortran 2008 HDF5 interface
guess_chunk_size Subroutine
25 statements
Source File
subroutine guess_chunk_size(dims, chunk_size)
based on https://github.com/h5py/h5py/blob/master/h5py/_hl/filters.py refer to https://support.hdfgroup.org/HDF5/Tutor/layout.html Repeatedly loop over the axes, dividing them by 2. Stop when: 1a. We're smaller than the target chunk size, OR 1b. We're within 50% of the target chunk size, AND 2. The chunk is smaller than the maximum chunk size
Element size larger than CHUNK_MAX
Arguments
Type Intent Optional Attributes Name
integer(kind=HSIZE_T), intent(in) :: dims(:)
integer(kind=HSIZE_T), intent(out) :: chunk_size(:)
Called by
Contents
None
Call graph
hdf_set_deflate calls guess_chunk_size
hdf_setup_write calls hdf_set_deflate
hdf_write_8d calls hdf_setup_write
hdf_write_1d calls hdf_setup_write, hdf_write_1d
hdf_write_4d calls hdf_setup_write, hdf_write_4d
hdf_write_2d calls hdf_setup_write, hdf_write_2d
hdf_write_3d calls hdf_setup_write, hdf_write_3d
hdf_write_7d calls hdf_setup_write, hdf_write_7d
hdf_write_5d calls hdf_setup_write, hdf_write_5d
hdf_write_scalar calls hdf_setup_write, hdf_write_scalar
hdf_write_6d calls hdf_setup_write, hdf_write_6d