hdf_close_group – Object-oriented Fortran HDF5 interface
hdf_close_group Module Procedure
11 statements
Source File
module procedure hdf_close_group module subroutine hdf_close_group(self, ierr) Interface →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(inout) :: self
integer, intent(out), optional :: ierr
Calls
Called by
Contents
None
Call graph
hdf_close_group calls check, h5gclose_f, hdf_close_group