hdf_write_scalar – Object-oriented Fortran 2008 HDF5 interface
hdf_write_scalar Module Procedure
35 statements
Source File
module procedure hdf_write_scalar module subroutine hdf_write_scalar(self, dname, value, ierr) Interface →
NOTE: 0d does not use chunk_size
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(inout) :: self
character(len=*), intent(in) :: dname
class(*), intent(in) :: value
integer, intent(out), optional :: ierr
Calls
Called by
Contents
None
Call graph
hdf_write_scalar calls hdf_setup_write, check, h5ltmake_dataset_string_f, hdf_write_scalar
hdf_setup_write calls check, hdf_set_deflate, h5dopen_f, h5ltpath_valid_f, hdf_shape_check, h5dcreate_f, h5pclose_f, h5screate_f
hdf_set_deflate calls check, h5pset_shuffle_f, h5pcreate_f, h5pset_deflate_f, guess_chunk_size, h5pset_fletcher32_f
hdf_shape_check calls check, h5ltget_dataset_ndims_f, h5ltget_dataset_info_f