hdf_get_slice – Object-oriented Fortran HDF5 interface
hdf_get_slice Subroutine
63 statements
Source File
public subroutine hdf_get_slice(self, dname, did, sid, mem_sid, i0, i1, i2)
setup array slices for read and write istart iend
stride
compensate for 0-based hyperslab vs. 1-based Fortran some callers have already opened the dataset. 0 is a sentinel saying not opened yet.
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
integer(kind=HID_T), intent(inout) :: did
integer(kind=hid_t), intent(out) :: sid
integer(kind=hid_t), intent(out) :: mem_sid
class(*), intent(in), dimension(:) :: i0
class(*), intent(in), dimension(:) :: i1
class(*), intent(in), optional dimension(:) :: i2
Calls
Called by
Contents
None
Call graph
hdf_get_slice calls h5dopen_f, h5dget_space_f, h5sselect_hyperslab_f
hdf_read_3d calls hdf_get_slice, hdf_read_3d
hdf_read_2d calls hdf_get_slice, hdf_read_2d
hdf_read_7d calls hdf_get_slice, hdf_read_7d
hdf_read_6d calls hdf_get_slice, hdf_read_6d
hdf_read_4d calls hdf_get_slice, hdf_read_4d
hdf_read_5d calls hdf_get_slice, hdf_read_5d
hdf_read_1d calls hdf_get_slice, hdf_read_1d