hdf_read_4d – Object-oriented Fortran HDF5 interface
hdf_read_4d Module Procedure
76 statements
Source File
module procedure hdf_read_4d module subroutine hdf_read_4d(self, dname, value, ierr, istart, iend, stride) Interface →
necessary to use this present check for Intel and GCC cast the dataset read from disk to the variable type presented by user h5f%read("/my_dataset", x) We only cast when needed to save memory. select case doesn't allow H5T_*
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
class(*), intent(out) :: value(:,:,:,:)
integer, intent(out), optional :: ierr
integer, intent(in), optional dimension(:) :: istart
integer, intent(in), optional dimension(:) :: iend
integer, intent(in), optional dimension(:) :: stride
Calls
Called by
Contents
None
Call graph
hdf_read_4d calls h5dread_f, hdf_wrapup, hdf_get_slice, check, get_native_dtype, h5dopen_f, hdf_shape_check, hdf_read_4d
hdf_wrapup calls check, h5dclose_f, h5sclose_f
hdf_get_slice calls h5dopen_f, h5dget_space_f, h5sselect_hyperslab_f
get_native_dtype calls h5dget_type_f, h5tget_native_type_f, h5tget_class_f, h5tclose_f, h5tget_size_f
hdf_shape_check calls h5ltget_dataset_ndims_f, h5ltget_dataset_info_f