hdf_set_deflate – Object-oriented Fortran 2018 HDF5 interface
hdf_set_deflate Module Procedure
19 statements
Source File
module procedure hdf_set_deflate module subroutine hdf_set_deflate(self, dims) Interface →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(inout) :: self
integer(kind=HSIZE_T), intent(in) :: dims(:)
Calls
Called by
Contents
None
Call graph
hdf_set_deflate calls h5pcreate_f, h5pset_chunk_f, h5pset_deflate_f, h5pset_shuffle_f, hdf_set_deflate
hdf_setup_write calls hdf_set_deflate, hdf_setup_write
hdf_add_real64_4d calls hdf_setup_write, hdf_add_real64_4d
hdf_add_real64_2d calls hdf_setup_write, hdf_add_real64_2d
hdf_add_real64_6d calls hdf_setup_write, hdf_add_real64_6d
hdf_add_real64_7d calls hdf_setup_write, hdf_add_real64_7d
hdf_add_int_6d calls hdf_setup_write, hdf_add_int_6d
hdf_add_real32_3d calls hdf_setup_write, hdf_add_real32_3d
hdf_add_int_4d calls hdf_setup_write, hdf_add_int_4d
hdf_add_real32_2d calls hdf_setup_write, hdf_add_real32_2d
hdf_add_real32_6d calls hdf_setup_write, hdf_add_real32_6d
hdf_add_int_5d calls hdf_setup_write, hdf_add_int_5d
hdf_add_real32_7d calls hdf_setup_write, hdf_add_real32_7d
hdf_add_int_7d calls hdf_setup_write, hdf_add_int_7d
hdf_add_real64_3d calls hdf_setup_write, hdf_add_real64_3d
hdf_add_int_2d calls hdf_setup_write, hdf_add_int_2d
hdf_add_real32_4d calls hdf_setup_write, hdf_add_real32_4d
hdf_add_int_3d calls hdf_setup_write, hdf_add_int_3d
hdf_add_real64_5d calls hdf_setup_write, hdf_add_real64_5d
hdf_add_real32_5d calls hdf_setup_write, hdf_add_real32_5d