hdf_get_int_3d – object-oriented Fortran 2018 HDF5 interface
hdf_get_int_3d Module Procedure
10 statements
Source File
module procedure hdf_get_int_3d module subroutine hdf_get_int_3d(self, dname, value) Interface →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
integer(kind=int32), intent(out), allocatable :: value(:,:,:)
Calls
Called by
Contents
None
Call graph
hdf_get_int_3d calls h5ltget_dataset_info_f, h5ltread_dataset_f, h5kind_to_type, hdf_get_int_3d