hdf_setup_write – Object-oriented Fortran 2008 HDF5 interface
hdf_setup_write Subroutine
44 statements
Source File
subroutine hdf_setup_write(self, dname, dtype, dims, sid, did, ierr, chunk_size)
open dataset
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(inout) :: self
character(len=*), intent(in) :: dname
integer(kind=HID_T), intent(in) :: dtype
integer(kind=HSIZE_T), intent(in) :: dims(:)
integer(kind=HID_T), intent(out) :: sid
integer(kind=HID_T), intent(out) :: did
integer, intent(out) :: ierr
integer, intent(in), optional :: chunk_size(:)
Calls
Called by
Contents
None
Call graph
hdf_setup_write calls hdf_set_deflate, h5dopen_f, h5ltpath_valid_f, hdf_shape_check, h5dcreate_f, check, h5pclose_f, h5screate_f
hdf_set_deflate calls check, h5pset_shuffle_f, h5pcreate_f, h5pset_deflate_f, guess_chunk_size, h5pset_fletcher32_f
hdf_shape_check calls check, h5ltget_dataset_ndims_f, h5ltget_dataset_info_f
hdf_write_8d calls hdf_setup_write
hdf_write_1d calls hdf_setup_write, hdf_write_1d
hdf_write_4d calls hdf_setup_write, hdf_write_4d
hdf_write_2d calls hdf_setup_write, hdf_write_2d
hdf_write_3d calls hdf_setup_write, hdf_write_3d
hdf_write_7d calls hdf_setup_write, hdf_write_7d
hdf_write_5d calls hdf_setup_write, hdf_write_5d
hdf_write_scalar calls hdf_setup_write, hdf_write_scalar
hdf_write_6d calls hdf_setup_write, hdf_write_6d