hdf_create – Object-oriented Fortran HDF5 interface
hdf_create Module Procedure
59 statements
Source File
module procedure hdf_create module subroutine hdf_create(self, dname, dtype, dims, sid, did, chunk_size, istart, iend, stride, compact) Interface →
h5lexists_f can false error with groups--just use h5ltpath_valid
stricter than self%exists() since we're creating and/or writing variable FIXME: read and write slice shape not checked; but should check in future versions open dataset Only new datasets go past this point create properties
don't set COMPACT after CHUNKED, will fail. And it's either or anyway. 64000 byte limit, here we assumed 8 bytes / element create dataspace create dataset
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(inout) :: self
character(len=*), intent(in) :: dname
integer(kind=HID_T), intent(in) :: dtype
integer(kind=HSIZE_T), intent(in) :: dims(:)
integer(kind=HID_T), intent(out), optional :: sid
integer(kind=HID_T), intent(out), optional :: did
integer, intent(in), optional :: chunk_size(:)
integer, intent(in), optional :: istart(:)
integer, intent(in), optional :: iend(:)
integer, intent(in), optional :: stride(:)
logical, intent(in), optional :: compact
keep istart, iend, stride for future slice shape check
Calls
Called by
Contents
None
Call graph
hdf_create calls h5dcreate_f, h5screate_f, h5dget_space_f, hdf_wrapup, set_deflate, h5dopen_f, h5pset_layout_f, check, h5pclose_f, h5pcreate_f, h5ltpath_valid_f, hdf_create
hdf_wrapup calls check, h5dclose_f, h5sclose_f
set_deflate calls check, h5pcreate_f, h5pset_shuffle_f, h5pset_fletcher32_f, guess_chunk_size, h5pset_deflate_f
hdf_write_scalar_i64 calls hdf_create, hdf_write_scalar_i64
hdf_write_scalar_i32 calls hdf_create, hdf_write_scalar_i32
hdf_write_scalar_r64 calls hdf_create, hdf_write_scalar_r64
hdf_write_scalar_r32 calls hdf_create, hdf_write_scalar_r32
hdf_write_8d calls hdf_create