hdf_get_real64 – object-oriented Fortran 2018 HDF5 interface
hdf_get_real64 Module Procedure
10 statements
Source File
module procedure hdf_get_real64 module subroutine hdf_get_real64(self, dname, value) Interface →
open dataset read dataset close dataset
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
real(kind=real64), intent(out) :: value
Calls
Called by
Contents
None
Call graph
hdf_get_real64 calls h5dclose_f, h5dread_f, h5dopen_f, h5kind_to_type, hdf_get_real64