hdf_add_real32_4d – Object-oriented Fortran 2018 HDF5 interface
hdf_add_real32_4d Module Procedure
11 statements
Source File
module procedure hdf_add_real32_4d module subroutine hdf_add_real32_4d(self, dname, value, chunk_size) Interface →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(inout) :: self
character(len=*), intent(in) :: dname
real(kind=real32), intent(in) :: value(:,:,:,:)
integer, intent(in), optional :: chunk_size(:)
Calls
Called by
Contents
None
Call graph
hdf_add_real32_4d calls h5kind_to_type, hdf_wrapup, h5dwrite_f, hdf_setup_write, hdf_add_real32_4d
hdf_wrapup calls hdf_wrapup, h5sclose_f, h5pclose_f, h5dclose_f
hdf_setup_write calls hdf_setup_write, hdf_set_deflate, h5dcreate_f
hdf_set_deflate calls hdf_set_deflate, h5pcreate_f, h5pset_chunk_f, h5pset_deflate_f, h5pset_shuffle_f