hdf_write_scalar_i64 – Object-oriented Fortran HDF5 interface
hdf_write_scalar_i64 Module Procedure
13 statements
Source File
module procedure hdf_write_scalar_i64 module subroutine hdf_write_scalar_i64(self, dname, value, ierr, compact) Interface →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(inout) :: self
character(len=*), intent(in) :: dname
integer(kind=int64), intent(in) :: value
integer, intent(out), optional :: ierr
logical, intent(in), optional :: compact
Calls
Called by
Contents
None
Call graph
hdf_write_scalar_i64 calls hdf_create, check, h5dwrite_f, hdf_wrapup, hdf_write_scalar_i64
hdf_create calls hdf_create, check, hdf_wrapup, h5dcreate_f, h5screate_f, h5dget_space_f, set_deflate, h5dopen_f, h5pset_layout_f, h5pclose_f, h5pcreate_f, h5ltpath_valid_f
hdf_wrapup calls check, h5dclose_f, h5sclose_f
set_deflate calls check, h5pcreate_f, h5pset_shuffle_f, guess_chunk_size, h5pset_deflate_f, h5pset_fletcher32_f