hdf_shape_check – Object-oriented Fortran 2008 HDF5 interface
hdf_shape_check Subroutine
28 statements
Source File
public subroutine hdf_shape_check(self, dname, dims, ierr)
check for matching rank, else bad reads can occur--doesn't always crash without this check check for matching size, else bad reads can occur.
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
integer(kind=HSIZE_T), intent(in) :: dims(:)
integer, intent(out) :: ierr
Calls
Called by
Contents
None
Call graph
hdf_shape_check calls check, h5ltget_dataset_info_f, h5ltget_dataset_ndims_f
hdf_read_4d calls hdf_shape_check, hdf_read_4d
hdf_read_5d calls hdf_shape_check, hdf_read_5d
hdf_setup_write calls hdf_shape_check
hdf_read_3d calls hdf_shape_check, hdf_read_3d
hdf_read_6d calls hdf_shape_check, hdf_read_6d
hdf_read_1d calls hdf_shape_check, hdf_read_1d
hdf_read_7d calls hdf_shape_check, hdf_read_7d
hdf_read_2d calls hdf_shape_check, hdf_read_2d
hdf_write_8d calls hdf_setup_write
hdf_write_2d calls hdf_setup_write, hdf_write_2d
hdf_write_4d calls hdf_setup_write, hdf_write_4d
hdf_write_1d calls hdf_setup_write, hdf_write_1d
hdf_write_3d calls hdf_setup_write, hdf_write_3d
hdf_write_7d calls hdf_setup_write, hdf_write_7d
hdf_write_5d calls hdf_setup_write, hdf_write_5d
hdf_write_scalar calls hdf_setup_write, hdf_write_scalar
hdf_write_6d calls hdf_setup_write, hdf_write_6d