hdf_initialize – Object-oriented Fortran HDF5 interface
hdf_initialize Subroutine
81 statements
Source File
private subroutine hdf_initialize(self, filename, ierr, status, action, comp_lvl, verbose, debug)
Opens hdf5 file
Initialize FORTRAN interface. get library version
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(inout) :: self
character(len=*), intent(in) :: filename
integer, intent(out), optional :: ierr
character(len=*), intent(in), optional :: status
character(len=*), intent(in), optional :: action
integer, intent(in), optional :: comp_lvl
logical, intent(in), optional :: verbose
logical, intent(in), optional :: debug
Calls
Contents
None
Call graph
hdf_initialize calls h5get_libversion_f, is_absolute_path, h5fopen_f, get_tempdir, h5fcreate_f, is_hdf5, check, h5open_f, h5eset_auto_f
is_absolute_path calls is_absolute_path
get_tempdir calls get_tempdir
is_hdf5 calls h5fis_hdf5_f