hdf_read_scalar – Object-oriented Fortran HDF5 interface
hdf_read_scalar Module Procedure
97 statements
Source File
module procedure hdf_read_scalar module subroutine hdf_read_scalar(self, dname, value, ierr) Interface →
cast the dataset read from disk to the variable type presented by user h5f%read("/my_dataset", x) We only cast when needed to save memory. select case doesn't allow H5T_*
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
class(*), intent(inout) :: value
intent(inout) for character
integer, intent(out), optional :: ierr
Calls
Called by
Contents
None
Call graph
hdf_read_scalar calls h5dread_f, hdf_wrapup, h5ltread_dataset_string_f, check, get_native_dtype, h5dopen_f, hdf_read_scalar
hdf_wrapup calls check, h5dclose_f, h5sclose_f
get_native_dtype calls h5dget_type_f, h5tget_native_type_f, h5tget_class_f, h5tclose_f, h5tget_size_f