hdf_add_real64 – object-oriented Fortran 2018 HDF5 interface
hdf_add_real64 Module Procedure
14 statements
Source File
module procedure hdf_add_real64 module subroutine hdf_add_real64(self, dname, value) Interface →
create dataspace create dataset write dataset close space and dataset
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
real(kind=real64), intent(in) :: value
Calls
Called by
Contents
None
Call graph
hdf_add_real64 calls h5dcreate_f, h5dclose_f, h5dwrite_f, h5screate_f, h5kind_to_type, h5sclose_f, hdf_add_real64