is_hdf5 – Object-oriented Fortran HDF5 interface
is_hdf5 Function
8 statements
Source File
public function is_hdf5(filename)
is this file HDF5?
avoid warning/error messages sometimes h5fis_hdf5_f is .true. for missing file
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
Return Value logical
Calls
Called by
Contents
None
Call graph
is_hdf5 calls h5fis_hdf5_f
test_exist calls is_hdf5
hdf_initialize calls is_hdf5
test_is_hdf5 calls is_hdf5
exist_tests calls test_exist, test_is_hdf5