lt2write_i64 – Object-oriented Fortran HDF5 interface
lt2write_i64 Module Procedure
3 statements
Source File
module procedure lt2write_i64 module subroutine lt2write_i64(filename, dname, value, ierr) Interface →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
character(len=*), intent(in) :: dname
integer(kind=int64), intent(in) :: value(:,:)
integer, intent(out), optional :: ierr
Called by
Contents
None
Call graph
lt2write_i64 calls lt2write_i64
h5write calls lt2write_i64
test_exist calls h5write
test_lt calls h5write
exist_tests calls test_exist