print_layout – Object-oriented Fortran HDF5 interface
print_layout Subroutine
26 statements
Source File
public subroutine print_layout(filename, ds_name)
prints dataset (variable) layout in a file get file size. get dataset storage layout not truly constants, so select case doesn't work
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
character(len=*), intent(in) :: ds_name
Calls
Contents
None
Call graph
print_layout calls h5dclose_f, h5fclose_f, h5dget_create_plist_f, h5pget_layout_f, h5fopen_f, h5close_f, h5dopen_f, h5fget_filesize_f, h5pclose_f