readattr_char_lt – Object-oriented Fortran HDF5 interface
readattr_char_lt Module Procedure
9 statements
Source File
module procedure readattr_char_lt module subroutine readattr_char_lt(filename, dname, attr, attrval, ierr) Interface →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
character(len=*), intent(in) :: dname
character(len=*), intent(in) :: attr
character(len=*), intent(inout) :: attrval
intent(inout) for character
integer, intent(out), optional :: ierr
Calls
Called by
Contents
None
Call graph
readattr_char_lt calls check, readattr_char_lt
h5read_attr calls readattr_char_lt
test_attributes calls h5read_attr