test_readwrite_lt – Object-oriented Fortran 2008 HDF5 interface
test_readwrite_lt Subroutine
46 statements
Source File
public subroutine test_readwrite_lt(path)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
Calls
Called by
Contents
None
Call graph
test_readwrite_lt calls h5write, h5read
h5write calls lt3write, lt7write, lt1write, lt2write, lt4write, lt5write, lt0write, lt6write
h5read calls lt4read, lt2read, lt7read, lt0read, lt6read, lt3read, lt5read, lt1read
lt3write calls lt3write, check
lt7write calls lt7write, check
lt4read calls lt4read, check
lt2read calls lt2read, check
lt1write calls lt1write, check
lt2write calls lt2write, check
lt7read calls lt7read, check
lt0read calls lt0read, check
lt4write calls lt4write, check
lt5write calls lt5write, check
lt6read calls lt6read, check
lt0write calls lt0write, check
lt3read calls lt3read, check
lt5read calls lt5read, check
lt1read calls lt1read, check
lt6write calls lt6write, check
test_hdf5 calls test_readwrite_lt