verify_data – Object-oriented Fortran HDF5 interface
verify_data Subroutine
9 statements
Source File
subroutine verify_data(filename)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
Calls
Called by
Contents
None
Call graph
verify_data calls read_int64, h5fopen_f, h5fclose_f
read_int64 calls h5kind_to_type, h5dclose_f, h5dopen_f
main_int64 calls verify_data