write_data – Object-oriented Fortran HDF5 interface
write_data Subroutine
9 statements
Source File
subroutine write_data(filename)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
Calls
Called by
Contents
None
Call graph
write_data calls h5fcreate_f, write_int64, h5fclose_f
write_int64 calls h5dclose_f, h5dcreate_f, h5screate_f, h5sclose_f, h5kind_to_type
main_int64 calls write_data