writeattr – Object-oriented Fortran 2018 HDF5 interface
writeattr Module Procedure
13 statements
Source File
module procedure writeattr module subroutine writeattr(self, dname, attr, attrval) Interface →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
character(len=*), intent(in) :: attr
character(len=*), intent(in) :: attrval
Calls
Called by
Contents
None
Call graph
writeattr calls h5ltpath_valid_f, h5ltset_attribute_string_f, writeattr