write_int64 – Object-oriented Fortran HDF5 interface
write_int64 Subroutine
12 statements
Source File
subroutine write_int64(fid, i, name)
dataspace
create the dataset.
write data
close handles
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t) :: fid
integer(kind=int64), intent(in) :: i
character(len=*), intent(in) :: name
Calls
Called by
Contents
None
Call graph
write_int64 calls h5dclose_f, h5dcreate_f, h5screate_f, h5sclose_f, h5kind_to_type
write_data calls write_int64
main_int64 calls write_data