write_layout – Object-oriented Fortran HDF5 interface
write_layout Subroutine
26 statements
Source File
public subroutine write_layout(file_id, ds_name, layout, dat)
write real data with HDF5 layout type specified
create dataspace create dataset property list config for dataset normally chunk size set more effectively for actual large datasets. create dataset write data
close
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: file_id
character(len=*), intent(in) :: ds_name
integer, intent(in) :: layout
real, intent(in) :: dat(:)
Calls
Called by
Contents
None
Call graph
write_layout calls h5dcreate_f, h5dclose_f, h5dwrite_f, h5sclose_f, h5pset_layout_f, h5pclose_f, h5pcreate_f
bench_write calls write_layout
compact calls bench_write