name: build-example
description: Build and test examples

runs:

  using: composite

  steps:

  - name: CMake Workflow
    shell: bash
    run: cmake --workflow reldebug

  - name: install package
    shell: bash
    run: cmake --install build

  - name: example workflow
    shell: bash
    working-directory: example
    run: cmake --workflow default
