create_softlink – Object-oriented Fortran HDF5 interface
create_softlink Interface
24 statements
Source File
interface
Calls
private module subroutine create_softlink(self, target, link) Implementation →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(inout) :: self
character(len=*), intent(in) :: target
character(len=*), intent(in) :: link
Call graph
create_softlink calls create_softlink, check, h5lcreate_soft_f