h5read – Object-oriented Fortran 2008 HDF5 interface
h5read Interface
3 statements
Source File
public interface h5read
Calls
Called by
Contents
Module Procedures
lt0read lt1read lt2read lt3read lt4read lt5read lt6read lt7read
Module Procedures
private interface lt0read()
Submodules
Arguments
None
private interface lt1read()
Submodules
Arguments
None
private interface lt2read()
Submodules
Arguments
None
private interface lt3read()
Submodules
Arguments
None
private interface lt4read()
Submodules
Arguments
None
private interface lt5read()
Submodules
Arguments
None
private interface lt6read()
Submodules
Arguments
None
private interface lt7read()
Submodules
Arguments
None
Call graph
h5read calls lt4read, lt2read, lt0read, lt3read, lt6read, lt5read, lt1read, lt7read
lt4read calls lt4read, check
lt2read calls lt2read, check
lt0read calls lt0read, check
lt3read calls lt3read, check
lt6read calls lt6read, check
lt5read calls lt5read, check
lt1read calls lt1read, check
lt7read calls lt7read, check
test_readwrite_lt calls h5read
test_hdf5 calls test_readwrite_lt