h5read_attr – Object-oriented Fortran HDF5 interface
h5read_attr Interface
3 statements
Source File
public interface h5read_attr
Calls
Called by
Contents
Module Procedures
readattr_num_lt readattr_char_lt
Module Procedures
private interface readattr_num_lt()
Arguments
None
private interface readattr_char_lt()
Arguments
None
Call graph
h5read_attr calls readattr_char_lt, readattr_num_lt
readattr_char_lt calls readattr_char_lt, check
readattr_num_lt calls readattr_num_lt, check
test_attributes calls h5read_attr