hdf_get_shape – Object-oriented Fortran 2018 HDF5 interface
hdf_get_shape Interface
147 statements
Source File
interface
Submodules
Calls
public module subroutine hdf_get_shape(self, dname, dims, ierr) Implementation →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
integer(kind=HSIZE_T), intent(out), allocatable :: dims(:)
integer, intent(out) :: ierr
Call graph
hdf_get_shape calls hdf_get_shape, h5ltpath_valid_f, h5ltget_dataset_info_f, h5ltget_dataset_ndims_f