hdf_get_real32_5d – object-oriented Fortran 2018 HDF5 interface
hdf_get_real32_5d Interface
299 statements
Source File
interface
Submodules
Calls
public module subroutine hdf_get_real32_5d(self, dname, value) Implementation →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
real(kind=real32), intent(out), allocatable :: value(:,:,:,:,:)
Call graph
hdf_get_real32_5d calls hdf_get_real32_5d, h5ltget_dataset_info_f, h5ltread_dataset_f, h5kind_to_type