hdf_add_int_2d – object-oriented Fortran 2018 HDF5 interface
hdf_add_int_2d Interface
299 statements
Source File
interface
Submodules
Calls
public module subroutine hdf_add_int_2d(self, dname, value, chunk_size) Implementation →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(inout) :: self
character(len=*), intent(in) :: dname
integer(kind=int32), intent(in) :: value(:,:)
integer, intent(in), optional :: chunk_size(:)
Call graph
hdf_add_int_2d calls hdf_add_int_2d, h5dwrite_f, hdf_setup_write, hdf_wrapup, h5kind_to_type
hdf_setup_write calls hdf_setup_write, h5dcreate_f, h5screate_simple_f, hdf_set_deflate
hdf_wrapup calls hdf_wrapup, h5dclose_f, h5sclose_f, h5pclose_f
hdf_set_deflate calls hdf_set_deflate, h5pset_deflate_f, h5pset_chunk_f, h5pset_shuffle_f, h5pcreate_f