hdf_get_chunk – Object-oriented Fortran 2008 HDF5 interface
hdf_get_chunk Interface
232 statements
Source File
interface
Submodules
Calls
private module subroutine hdf_get_chunk(self, dname, chunk_size) Implementation →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
integer(kind=hsize_t), intent(out) :: chunk_size(:)
Call graph
hdf_get_chunk calls hdf_get_chunk, h5dget_create_plist_f, h5dopen_f, h5ltget_dataset_ndims_f, h5pget_chunk_f, h5dclose_f, check