hdf_get_layout – Object-oriented Fortran 2008 HDF5 interface
hdf_get_layout Interface
232 statements
Source File
interface
Submodules
Calls
private module function hdf_get_layout(self, dname) result(layout) Implementation →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
Return Value integer
Description
H5D_CONTIGUOUS_F, H5D_CHUNKED_F, H5D_VIRTUAL_F, H5D_COMPACT_F
Call graph
hdf_get_layout calls hdf_get_layout, h5pget_layout_f, h5dget_create_plist_f, h5dopen_f, h5dclose_f, check