hdf_add_real32 – object-oriented Fortran 2018 HDF5 interface
hdf_add_real32 Interface
299 statements
Source File
interface
Submodules
Calls
public module subroutine hdf_add_real32(self, dname, value) Implementation →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
real(kind=real32), intent(in) :: value
Call graph
hdf_add_real32 calls hdf_add_real32, h5dcreate_f, h5dclose_f, h5dwrite_f, h5screate_f, h5kind_to_type, h5sclose_f