hdf_write_2d – Object-oriented Fortran 2018 HDF5 interface
hdf_write_2d Interface
147 statements
Source File
interface
Submodules
Calls
public module subroutine hdf_write_2d(self, dname, value, ierr, chunk_size) Implementation →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(inout) :: self
character(len=*), intent(in) :: dname
class(*), intent(in) :: value(:,:)
integer, intent(out) :: ierr
integer, intent(in), optional :: chunk_size(:)
Call graph
hdf_write_2d calls hdf_write_2d, hdf_setup_write, hdf_wrapup, h5kind_to_type, h5dwrite_f
hdf_setup_write calls hdf_setup_write, h5ltpath_valid_f, h5dopen_f, hdf_set_deflate, h5dcreate_f, h5screate_f
hdf_wrapup calls hdf_wrapup, h5dclose_f, h5sclose_f, h5pclose_f
hdf_set_deflate calls hdf_set_deflate, h5pset_shuffle_f, h5pset_chunk_f, h5pset_deflate_f, h5pcreate_f