hdf_setup_read – Object-oriented Fortran 2018 HDF5 interface
hdf_setup_read Interface
147 statements
Source File
interface
Submodules
Calls
Called by
public module subroutine hdf_setup_read(self, dname, dims, ierr) Implementation →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
integer(kind=HSIZE_T), intent(out) :: dims(:)
integer, intent(out) :: ierr
Call graph
hdf_setup_read calls hdf_setup_read, h5ltpath_valid_f, h5ltget_dataset_info_f
hdf_read_2d calls hdf_setup_read, hdf_read_2d
hdf_read_5d calls hdf_setup_read, hdf_read_5d
hdf_read_1d calls hdf_setup_read, hdf_read_1d
hdf_read_7d calls hdf_setup_read, hdf_read_7d
hdf_read_4d calls hdf_setup_read, hdf_read_4d
hdf_read_3d calls hdf_setup_read, hdf_read_3d
hdf_read_6d calls hdf_setup_read, hdf_read_6d