hdf_read_5d – Object-oriented Fortran 2008 HDF5 interface
hdf_read_5d Interface
232 statements
Source File
interface
Submodules
Calls
private module subroutine hdf_read_5d(self, dname, value, ierr, istart, iend, stride) Implementation →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
class(*), intent(out) :: value(:,:,:,:,:)
integer, intent(out), optional :: ierr
integer, intent(in), optional dimension(:) :: istart
integer, intent(in), optional dimension(:) :: iend
integer, intent(in), optional dimension(:) :: stride
Call graph
hdf_read_5d calls hdf_read_5d, hdf_get_slice, hdf_shape_check, h5dread_f
hdf_get_slice calls h5dopen_f
hdf_shape_check calls check, h5ltget_dataset_info_f, h5ltget_dataset_ndims_f