hdf_add_int – object-oriented Fortran 2018 HDF5 interface
hdf_add_int Interface
299 statements
Source File
interface
Submodules
Calls
public module subroutine hdf_add_int(self, dname, value) Implementation →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
integer(kind=int32), intent(in) :: value
Call graph
hdf_add_int calls hdf_add_int, h5dcreate_f, h5dclose_f, h5dwrite_f, h5screate_f, h5kind_to_type, h5sclose_f