readattr_num – Object-oriented Fortran HDF5 interface
readattr_num Interface
50 statements
Source File
interface
Calls
private module subroutine readattr_num(self, dname, attr, attrval, ierr) Implementation →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
character(len=*), intent(in) :: attr
class(*), intent(out) :: attrval(:)
integer, intent(out), optional :: ierr
Call graph
readattr_num calls readattr_num, h5ltget_attribute_double_f, check, h5ltget_attribute_int_f, h5ltget_attribute_float_f