writeattr_num – Object-oriented Fortran HDF5 interface
writeattr_num Interface
50 statements
Source File
interface
Calls
private module subroutine writeattr_num(self, dname, attr, attrval, ierr) Implementation →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
character(len=*), intent(in) :: attr
class(*), intent(in) :: attrval(:)
integer, intent(out), optional :: ierr
Call graph
writeattr_num calls writeattr_num, check, h5ltset_attribute_float_f, h5ltset_attribute_double_f, h5ltset_attribute_int_f