writeattr_char – Object-oriented Fortran HDF5 interface
writeattr_char Interface
50 statements
Source File
interface
Calls
private module subroutine writeattr_char(self, dname, attr, attrval, ierr) Implementation →
Arguments
Type Intent Optional Attributes Name
class(hdf5_file), intent(in) :: self
character(len=*), intent(in) :: dname
character(len=*), intent(in) :: attr
character(len=*), intent(in) :: attrval
integer, intent(out), optional :: ierr
Call graph
writeattr_char calls writeattr_char, check, h5ltset_attribute_string_f