array_test – Object-oriented Fortran HDF5 interface
array_test Program
143 statements
Source File
Uses
ieee_arithmetic
iso_fortran_env
h5fortran
Calls
Contents
Variables
nan
Subroutines
test_basic_array test_read_slice test_write_slice test_readwrite_array
Variables
Type Attributes Name Initial
real(kind=real32) :: nan
Subroutines
subroutine test_basic_array(filename)
read int32 verify reading into larger array real
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
tests that compression doesn't fail for very small datasets, where it really shouldn't be used (makes file bigger)
subroutine test_read_slice(filename)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
subroutine test_write_slice(filename)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
subroutine test_readwrite_array(filename, ng, nn, pn)
more group
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
integer, intent(in) :: ng
integer, intent(in) :: nn
integer, intent(in) :: pn
Call graph
array_test calls test_write_slice, test_read_slice, test_readwrite_array, test_basic_array