compact – Object-oriented Fortran HDF5 interface
compact Program
22 statements
Source File
Uses
hdf5
h5layout
dummy data
Fortran interface
Calls
Contents
Variables
N M ierr fn1 fn2 fn3 x
Variables
Type Attributes Name Initial
integer :: N
integer :: M
integer :: ierr
character(len=:), allocatable :: fn1
character(len=:), allocatable :: fn2
character(len=:), allocatable :: fn3
real, allocatable :: x(:)
Call graph
compact calls h5open_f, h5close_f, bench_write, bench_read
bench_write calls h5fclose_f, write_layout, h5fcreate_f, sysclock2ms
bench_read calls h5fclose_f, h5fopen_f, sysclock2ms, h5ltread_dataset_float_f
write_layout calls h5dcreate_f, h5dclose_f, h5dwrite_f, h5sclose_f, h5pset_layout_f, h5pclose_f, h5pcreate_f