exist_tests – Object-oriented Fortran HDF5 interface
exist_tests Program
81 statements
Source File
Uses
iso_fortran_env
h5fortran
test "exist" variable
Calls
Contents
Subroutines
test_is_hdf5 test_exist test_softlink test_scratch test_multifiles
Subroutines
subroutine test_is_hdf5()
Arguments
None
subroutine test_exist()
Arguments
None
subroutine test_softlink()
test dangling link
Arguments
None
subroutine test_scratch()
Arguments
None
subroutine test_multifiles()
Arguments
None
Call graph
exist_tests calls test_softlink, test_exist, test_scratch, test_is_hdf5, test_multifiles
test_exist calls is_hdf5, h5write, h5exist
test_is_hdf5 calls is_hdf5
test_multifiles calls hdf5_close
is_hdf5 calls h5fis_hdf5_f
hdf5_close calls check, h5close_f
h5write calls lt5write_i32, lt0write_char, lt6write_i32, lt2write_r32, lt2write_r64, lt4write_r32, lt2write_i32, lt3write_i32, lt2write_i64, lt5write_r64, lt6write_r32, lt7write_i32, lt7write_r32, lt1write_i32, lt0write_r32, lt0write_i32, lt3write_r32, lt6write_r64, lt4write_i32, lt4write_r64, lt6write_i64, lt7write_r64, lt1write_i64, lt4write_i64, lt3write_r64, lt7write_i64, lt0write_i64, lt3write_i64, lt5write_i64, lt1write_r32, lt0write_r64, lt1write_r64, lt5write_r32
h5exist calls h5exist
lt5write_i32 calls lt5write_i32
lt0write_char calls lt0write_char
lt6write_i32 calls lt6write_i32
lt2write_r32 calls lt2write_r32
lt2write_r64 calls lt2write_r64
lt4write_r32 calls lt4write_r32
lt2write_i32 calls lt2write_i32
lt3write_i32 calls lt3write_i32
lt2write_i64 calls lt2write_i64
lt5write_r64 calls lt5write_r64
lt6write_r32 calls lt6write_r32
lt7write_i32 calls lt7write_i32
lt7write_r32 calls lt7write_r32
lt1write_i32 calls lt1write_i32
lt0write_r32 calls lt0write_r32
lt0write_i32 calls lt0write_i32
lt3write_r32 calls lt3write_r32
lt6write_r64 calls lt6write_r64
lt4write_i32 calls lt4write_i32
lt4write_r64 calls lt4write_r64
lt6write_i64 calls lt6write_i64
lt7write_r64 calls lt7write_r64
lt1write_i64 calls lt1write_i64
lt4write_i64 calls lt4write_i64
lt3write_r64 calls lt3write_r64
lt7write_i64 calls lt7write_i64
lt0write_i64 calls lt0write_i64
lt3write_i64 calls lt3write_i64
lt5write_i64 calls lt5write_i64
lt1write_r32 calls lt1write_r32
lt0write_r64 calls lt0write_r64
lt1write_r64 calls lt1write_r64
lt5write_r32 calls lt5write_r32