main_int64 – Object-oriented Fortran HDF5 interface
main_int64 Program
53 statements
Source File
Uses
hdf5
iso_fortran_env
hdf5 fortran interface can also read/write int64, but it's not in the h5lt interface initialize fortran interface and file
Calls
Contents
Variables
ierr filename
Functions
read_int64
Subroutines
verify_data write_data write_int64
Variables
Type Attributes Name Initial
integer :: ierr
character(len=:), allocatable :: filename
Functions
function read_int64(fid, name) result(i)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: fid
character(len=*), intent(in) :: name
Return Value integer(kind=int64)
Subroutines
subroutine verify_data(filename)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
subroutine write_data(filename)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
subroutine write_int64(fid, i, name)
dataspace
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t) :: fid
integer(kind=int64), intent(in) :: i
character(len=*), intent(in) :: name
Call graph
main_int64 calls write_data, h5close_f, h5open_f, verify_data
write_data calls write_int64, h5fclose_f, h5fcreate_f
verify_data calls h5fclose_f, read_int64, h5fopen_f
write_int64 calls h5dclose_f, h5dcreate_f, h5screate_f, h5sclose_f, h5kind_to_type
read_int64 calls h5dclose_f, h5kind_to_type, h5dopen_f