test_hdf5 – Object-oriented Fortran 2008 HDF5 interface
test_hdf5 Program
77 statements
Source File
Uses
iso_fortran_env
h5fortran
test_lt
test_array
test_scalar
test_string
unit tests and registration tests of HDF5 OO interface
Calls
Contents
Variables
path argv i l
Subroutines
testGroup test_write_attributes test_writeExistingVariable
Variables
Type Attributes Name Initial
character(len=:), allocatable :: path
character(len=256) :: argv
integer :: i
integer :: l
Subroutines
subroutine testGroup(path)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
subroutine test_write_attributes(path)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
subroutine test_writeExistingVariable(path)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
Call graph
test_hdf5 calls test_write_array, test_write_attributes, testgroup, test_writeexistingvariable, test_strip_null, test_lowercase, test_readwrite_lt, test_string_rw, test_scalar_rw, test_readwrite_array
test_write_array calls dims
test_strip_null calls strip_trailing_null
test_lowercase calls tolower
test_readwrite_lt calls h5write, h5read
test_string_rw calls truncate_string_null
h5write calls lt3write, lt7write, lt1write, lt2write, lt4write, lt5write, lt0write, lt6write
h5read calls lt4read, lt2read, lt7read, lt0read, lt6read, lt3read, lt5read, lt1read
lt3write calls lt3write, check
lt7write calls lt7write, check
lt4read calls lt4read, check
lt2read calls lt2read, check
lt1write calls lt1write, check
lt2write calls lt2write, check
lt7read calls lt7read, check
lt0read calls lt0read, check
lt4write calls lt4write, check
lt5write calls lt5write, check
lt6read calls lt6read, check
lt0write calls lt0write, check
lt3read calls lt3read, check
lt5read calls lt5read, check
lt1read calls lt1read, check
lt6write calls lt6write, check