test_file_image – Object-oriented Fortran HDF5 interface
test_file_image Program
18 statements
Source File
Uses
iso_fortran_env
file_image
Calls
Contents
Variables
fapl_id in out
Variables
Type Attributes Name Initial
integer(kind=hid_t) :: fapl_id
integer, dimension(1:8) :: in
arbitrary user data
integer, dimension(1:8) :: out
arbitrary user data
Call graph
test_file_image calls create_file_image, close_file_image, write_file_image, read_file_image
create_file_image calls h5pcreate_f, h5pget_file_image_f, h5open_f
close_file_image calls h5close_f, h5pclose_f
read_file_image calls h5pget_file_image_f