test_minimal – Object-oriented Fortran 2008 HDF5 interface
test_minimal Program
28 statements
Source File
Uses
hdf5
h5lt
Calls
Contents
Variables
ierr p lid filename argv i l
Variables
Type Attributes Name Initial
integer :: ierr
integer :: p
integer(kind=HID_T) :: lid
character(len=:), allocatable :: filename
character(len=256) :: argv
integer :: i
integer :: l
Call graph
test_minimal calls h5close_f, h5kind_to_type, h5open_f, h5fclose_f, h5fcreate_f