test_attributes – Object-oriented Fortran HDF5 interface
test_attributes Program
54 statements
Source File
Uses
iso_fortran_env
h5fortran
Calls
Contents
Variables
filename s32
Subroutines
test_write_attributes test_read_attributes
Variables
Type Attributes Name Initial
character(len=*), parameter :: filename = 'test_attr.h5'
character(len=8) :: s32
Subroutines
subroutine test_write_attributes(path)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
subroutine test_read_attributes(path)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
Call graph
test_attributes calls h5write_attr, test_write_attributes, i32, h5read_attr, test_read_attributes
h5write_attr calls writeattr_num_lt, writeattr_char_lt
h5read_attr calls readattr_char_lt, readattr_num_lt
readattr_char_lt calls readattr_char_lt, check
readattr_num_lt calls readattr_num_lt, check
writeattr_num_lt calls writeattr_num_lt, check
writeattr_char_lt calls writeattr_char_lt, check