test_error – Object-oriented Fortran 2008 HDF5 interface
test_error Program
101 statements
Source File
Uses
iso_fortran_env
h5fortran
Calls
Contents
Variables
h5f path argv i l
Subroutines
test_nonexist_old_file test_nonexist_unknown_file test_nonhdf5_file test_nonexist_variable test_wrong_type test_unknown_write test_unknown_read
Variables
Type Attributes Name Initial
type(hdf5_file) :: h5f
character(len=:), allocatable :: path
character(len=256) :: argv
integer :: i
integer :: l
Subroutines
subroutine test_nonexist_old_file(path)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
subroutine test_nonexist_unknown_file(path)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
subroutine test_nonhdf5_file(path)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
subroutine test_nonexist_variable(path)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
subroutine test_wrong_type(path)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
subroutine test_unknown_write(path)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
subroutine test_unknown_read(path)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
Call graph
test_error calls test_nonexist_old_file, test_nonexist_variable, test_unknown_write, test_nonexist_unknown_file, test_nonhdf5_file, test_wrong_type, test_unknown_read