if(CMAKE_BUILD_TYPE STREQUAL Debug)
  add_compile_options(-g -O0)
else()
  add_compile_options(-g -O3)
endif()

if(${CMAKE_Fortran_COMPILER_ID} STREQUAL Intel)

  if(CMAKE_BUILD_TYPE STREQUAL Debug)
    add_compile_options(-debug extended -check all -heap-arrays -fp-stack-check)
  endif()
  add_compile_options(-warn -traceback)
elseif(${CMAKE_Fortran_COMPILER_ID} STREQUAL GNU)
  add_compile_options(-march=native -fimplicit-none)
  
  if(CMAKE_BUILD_TYPE STREQUAL Debug)
    add_compile_options(-fcheck=all)
  endif()
  
  if(${CMAKE_Fortran_COMPILER_VERSION} VERSION_LESS 5.4.1)
    message(FATAL_ERROR " gfortran >= 5.4.1 required, you have " ${CMAKE_Fortran_COMPILER_VERSION})
  elseif(${CMAKE_Fortran_COMPILER_VERSION} VERSION_GREATER_EQUAL 8)
    add_compile_options(-std=f2018)
  endif()
  
  add_compile_options(-Wall -Wextra -Wpedantic -Werror=array-bounds)
elseif(${CMAKE_Fortran_COMPILER_ID} STREQUAL PGI)
  add_compile_options(-Mallocatable=03)
elseif(${CMAKE_Fortran_COMPILER_ID} STREQUAL Flang) 
  add_compile_options(-Mallocatable=03)
  link_libraries(-static-flang-libs)
elseif(${CMAKE_Fortran_COMPILER_ID} STREQUAL NAG)
  add_compile_options(-u -C=all)
endif()
