name: build

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CMAKE_INSTALL_PREFIX: ~/libs
  CMAKE_PREFIX_PATH: ~/libs
  CMAKE_GENERATOR: Ninja


on:
  push:
    paths:
      - "scripts/CMakeLists.txt"
      - "cmake/libraries.json"
      - "cmake/hdf5.cmake"
      - ".github/workflows/ci_build.yml"

jobs:

  linux_mac:
    timeout-minutes: 20

    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
        - os: macos-latest
          shared: false

    runs-on: ${{ matrix.os}}

    steps:
    - uses: actions/checkout@v6

    - name: GCC (macOS)
      if: runner.os == 'macOS'
      run: echo "FC=gfortran-15" >> $GITHUB_ENV

    - name: Configure HDF5 library
      run: cmake -S scripts -B scripts/build

    - name: Build/install HDF5
      run: cmake --build scripts/build

    - name: h5fortran workflow
      run: cmake --workflow default

    - name: install h5fortran
      run: cmake --install build

    - name: example workflow
      run: cmake --workflow default
      working-directory: example
